
export const enum MT{
	RegistAccount,
	OnRMBBuyCard,
	GetMyAccountPointJf,
	BindWx,
	LoginAccount,
	ChangePass,
	SelectedServer,
	CreateRole,
	DeleteRole,
	ChangeName,
	SwitchRoleType,
	GetSellRoleNeedMuPoint,
	SellRole,
	StarGame,
	ReStarGame,
	LoginGate,
	JoinLine,
	ReLoadMapOk,
	GetMyJf,
	ClientHeartBeat,
	BuyYk,
	DownMuPointFromMyAccount,
	GetMyAccountMuPoint,
	GetMyRoleList,
	HideMySidList,
	FocusChange,
	//========限制请求号======
	BuyLianTiVip,
	NewOtherIntoMySeeDis,
	DeleteOther,
	EndMove,
	MoveToPos,
	ResetPos,
	ChangePosFailed,
	OtherMoveTo,
	GetLineList,
	SendChatMsg,
	GetChatMsg,
	MonsterStartMoveTo,
	DeleteMonster,
	NewMonsterIntoMySeeDis,
	MonsterBeKilled,
	PlayerBeAtkByMonster,
	RoleAtkRole,
	ActiveLianTi,
	UpLianTi,
	SwitchLianTiType,
	RoleBeHealedByRole,
	UseSkill,
	MonsterBeAtkedByPlayer,
	DzAct,
	MonsterBeHealed,
	MonsterBeAtkedByMonster,
	Reset1Skill,
	MonsterGetBuffDmg,
	PlayerGetBuffDmg,
	GetNewEmail,
	SwitchAuto,
	RelifeAtHome,
	AutoGetHpMpAgSd,
	ToRandomPosition,
	BackHome,
	ChangeLine,
	GoToPosImmediate,
	GoToMapPoint,
	GoToMapPosByDoor,
	BackToPos,
	HandMoveToPos,
	DeleteOneEmail,
	PlayerLvUp,
	DeleteDropItem,
	TryPickUpOneDropItem,
	RecoverEquips,
	AutoRecoverEquips,
	DressEquip,
	UnDressEquip,
	OtherLvUp,
	GetBasePros,
	GetMorePros,
	AddPoint,
	ResetPoint,
	GetMyTeam,
	GetOtherTeams,
	GetNoTeamList,
	GetRequestList,
	SaveTeamSet,
	RequestJoinTeam,
	InviteOtherJoinMyTeam,
	ExitFromMyTeam,
	HitOutFromMyTeam,
	AgreeRequesterJoinMyTeam,
	ClearMyTeamRequestList,
	SwitchTeamOwner,
	OnTeamOwnerChanged,
	GetInviteMsg,
	AgreeBeInvitedJoinTeam,
	OtherChangeTeamId,//队伍变化时通知附近玩家，修改我的TeamId
	CreateTeam,
	OnJoinTeam,
	OnBeHitOutTeam,
	OnOtherBeHitOutTeam,
	OnOtherExitTeam,
	GetCkRoleList,
	GetRoleCk,
	MoveMyBagEquipIntoCk,
	MoveCkEquipIntoMyBag,
	MoveMyBagItemsIntoCk,
	MoveCkItemsIntoMyBag,
	GetOtherRoleInfo,
	GetFriends,
	AddFriend,
	DeleteFriend,
	GetMyShop,
	RegistShop,
	UpSellItem,
	ReUpSellItem,
	DownSellItem,
	CheckCanDownSellItem,
	DownShopCkItemToBag,
	GetMyNewHistory,
	GetMarket,
	BuyMarketItem,
	ClearMyHitory,
	PopShopPoint,
	PushPointToShop,
	PopShopDia,
	PushDiaToShop,
	DeleteAllEmails,
	LearnSkill,
	GetKillNums,
	SaveSkillSlots,
	ResetAllSkill,
	SwitchSkillMode,
	SwitchPkMode,
	BuyNpcShopItem,
	GetBossList,
	UpdateBuffs,
	FireBuffSkill,
	CallGoldMonster,
	SaveBagSet,
	CreateZm,
	ExitFromMyZm,
	HitOutFromMyZm,
	ChangeZmMenberJob,
	OnZmMenberJobChanged,
	SaveZmSet,
	GetMyZm,
	GetZmList,
	GetNoZmList,
	GetRequestJoinZmList,
	AgreeRequesterJoinMyZm,
	ClearZmRequestList,
	InviteOtherJoinMyZm,
	AgreeBeInvitedJoinZm,
	RequestJoinZm,
	ZmCheckIn,
	OnOtherJoinZm,
	OnBeHitOutZm,
	OnOtherBeHitOutZm,
	OnOtherExitZm,
	SwitchZmOwner,
	OnZmOwnerChanged,
	TanHeMz,
	UseItem,
	TryStartCircleQuest,
	CompleteQuest,
	GetNewQuest,
	UpdateQuest,
	GetQuestData,
	TalkToNPC,
	UpMuPointToMyAccount,
	ActiveXiangQian,
	XiangQianOn,
	XiangQianOff,
	XiangQianUp,
	HcPet,
	RhPet,
	XlPet,
	ResetPet,
	TunShi,//吞噬
	DoHc,//合成
	SaveTzSet,
	ResetXz,//勋章重置
	LockEquip,
	SetLockPass,
	ClearLockPass,
	MovePro,
	AddRoleTypeLv,//转职
	GetWorldBossList,
	DoZs,//转生
	UpdatePkEnemyList,
	Call1MyBoss,
	GetMyBossList,
	YjSdMyBoss,
	SdFb,
	FbIsStart,
	FbIsOver,
	ChangeChengHaoId,
	RegisterHole,
	GetMyHole,
	CollectMyHoleRemainInventory,
	MyHoleGetExp,
	GetRandomOtherHole,
	StartLootOtherHole,
	TryOpenOtherHoleGrid,
	ChangeMyHoleGrid,
	GetHoleHis,
	UseAllHoleOpenNum,
	SwitchHoleRandomMode,
	GetPh,
	GetNewSysGG,
	GetNewHuoDong,
	CallOthersToHere,
	LetOthersBack,
	StartMove,
	RelifeAtPlace,
	MoveMyBagItemsIntoDefaultCk,
	SwitchMyBossOwner,//转让我的BOSS给队友
	OtherSwitchMyBossOwner,
	AddCkCap,
	DeleteMyBoss,
	ActiveRoleType,
	GetBuffHoles,
	GetBuffHoleTeam,
	SeizeBuffHole,
	PkOver,
	StartSeizeBattle,
	GetMyAccountJf,
	DownJfFromMyAccount,
	GetMyJfReword,
	GetFirstKillWorldBoss,
	GetFirstKillWorldBossReword,
	GetMyFirstLvReword,//领取冲级排行奖励
	TryUseCdKey,
	GetXuYuanData,
	TryXuYuan,
	GetMyDiaShop,
	CreatNewOrder,
	CancelOrder,
	PopMoneyFromDiaMarket,
	GetMyDiaShopOrders,
	GetMyDiaShopPopHis,
	ResetEquipZy,
	DiaBuffChanged,
	BuyDiaBuff,
	CompleteAllDayQuest,
	LetOthersBackToSavedPos,
	SaveMemberPos,
	GetMyAccountGotLcBox,
	GotLcBoxFromMyAccount,
	YjKillPrivateWorldBoss,
	YjKillPrivateYwBoss,
	WorldBossIsRelive, //时间BOSS复活了
	SetWorldBossDeath,
	SouHun,
	YjSouHun,
	GetMyHunList,
	FuTiHun,
	HeChengHun,//用魂兽碎片抽魂兽
	UpHunLv,//升星（5个升为一个高1星的）
	FjHun,   //分解魂兽
	GetMyRankPkData,
	TryRankPk,
	GetRankPkPh,
	ExitPk,
	RankPkOver,
	GetRankPkPhReward,
	AllFailedRankPk,
	YjKillXsBoss,
	MoveMyManyBagItemsIntoCk,
	MoveManyCkItemsIntoMyBag,
	SetDefaultCkId,
	BagIsFull,
	GetMyAccountTgBoxNum,
	GetMyAccountTgBox,
	RegisterAccountTgCode,
	BindAccountTgCode,
	ChaiFen,
	GetShouTuList,
	ShouTu, //发布收徒信息
	BaiShi,
	GetMyShiTuData,
	GetShiFuReward, //获得师傅奖励
	GetTuDiReward,  //获得徒弟奖励
	HitOutTuDi,
	GetFailedAddRates,
	GetRemainHlwNums,
	TryNextTowerLv,
	SuccessTowerLv,
	GetCurLvTowerData,
	GetDiaPrice,
	GetTowerRankList,
	BuyKfShopItem,
	GetMyKfJf,//获取跨服积分
	ZmJuanZhu,          //战盟捐助
	ZmUpBuildLv,        //尝试升级建筑
	ZmSpeedUpBuildTime, //加速建造时间
	ZmAddOneHunter,     //增加一个狩猎场
	ZmUpZmBossTypeLv,   //激活指定战盟BOSS
	ZmBuyZmMemberCap,
	ZmReliveZmBoss, //复活一只战盟BOSS来击杀
	HuoDongChouJiang,
	GetHuoDongData,
	ZmGetMembers,
	ZmGetCk,
	ZmGetBoss,
	ZmGetDmgPh,
	ZmBuyGp,
	ZmBuyShopItem,
	ZmAtkBoss,
	ZmJsBoss,
	ZmAllToMe,
	ZmGetAllMyItem,
	ZmSetItemToOther,
	ZmGetNewCkActHis,
	SwitchEquipType,
	AddEquipZy,
	GetNewTeamPkHis,
	GetDayDoList,
	KfGcGetData,
	KfGcSignUp,
	KfGcAddHuDunExp,
	KfGcSwitchCellId,
	KfGcAtkCell,
	KfGcGetCellData,
	KfGcSetDefender,
	KfGcGetLastGcPh,
	GetHuoDongRewards,
	GetGemMarketItem,
	BuyGemMarketItem,
	SellGemMarketItem,
	GetHuoDongHcPh,
	GetHuoDongHcPhRewards,
	GetMyAccountTgPoint,
	RoleDrop1EquipAfterBeKilled,
	TryRequestTradeToOther,
	AgreeBeInvitedTrade,
	StartTrade,
	TradeAdd1Item,
	TradeDelete1Item,
	TradeItemsChanged,
	TradeOk,
	TradeCancel,
	TradeComplete,
	GetHcHisList,
	TryJoinGuessGame,
	TryLeaveGuessGame,
	GuessGameStart,
	Guess,
	GuessPhChanged,
	GuessGameStop,
	SdOneMyBoss,
	GetJiLabelReward,

	//不能大于这个数，大于20000为服务器内部通信编号
	Max = 20000
}
export const enum ConfigType{
    MaxBagCap,
	MaxCkCap, //仓库总容量上限
	MaxAddCkCap,
	ActiveLv_CircleQuest,
	ActiveLv_LianTi,
	ActiveLv_XiangQian,
	ActiveLv_YuanShen,
	CreateZmNeedDia,
	ExitZmCdTime,
	ZmQdGx,
	ResetPointFreeLv,
	ResetPointNeedDia,
	CallGoldMonsterNeedNum,
	CallRedMonsterNeedNum,
	GotoPosNeedDia,
	DefaultAtkCd,
	PlayerMinAtkCd,
	ActiveLv_Tower,
	ZmDiaCheckInGx,
	ZmDiaCheckInNeedDia,
	ResetPetMainYsNeedDia,
	ResetFuMoNeedDia0,
	ResetFuMoNeedDia1,
	ResetFuMoNeedDia2,
	ResetFuMoNeedDia3,
	LianTiBaseNeedGold,
	LianTiBaseNeedDia,
	ResetXunZhangNeedDia,
	MoveProPerLvNeedDia,
	ZhuanShengAddPoint, //每次转生送多少点
	ZhuanShengNeedBaseGold,//每次转生需要金币基数
	RedNameRedPointNum,
	KillOnePlayerAddRedPoint,
	PlayerSeeDis,
	MaxFbRoleNum,
	MaxLineRoleNum,
	SdFbNeedDia,
	ActiveLv_Hole,
	GetRandomOtherHoleNeedGold,
	JiHeActNeedDia,//集合指令需要多少钻石
	HandRelifeAtPlaceNeedDia,
	PlayerAutoRelifeCd,
	ZmDiaCheckInDayNum,
	SwitchMyBossOwnerNeedDia,
	AddCkCapNeedMuPoint,
	MaxShopCkCap,
	ActiveLvBuffHole,
	ActiveLvKfBuffHole,
	BuyLianTiVipNeedMuPoint,
	ActiveLvRankPk,
	ActiveLvKfRankPk,
	YjKillXsBossDayNum,
	SwitchYgTypeNeedDia,
	ZhuanShengNeedBaseDIa,
	BaiShiLv,
	ShouTuLv,
	ZmHomeBuildUpNeedDia,    //战盟大厅升级需要的钻石基数
	ZmHomeBuildUpNeedGx,     //战盟大厅升级需要的贡献基数
	ZmJTBuff1UpNeedDia,      //战盟祭坛科技升级需要的钻石:产量提升
	ZmJTBuff2UpNeedDia,      //战盟祭坛科技升级需要的钻石:生命增强
	ZmJTBuff3UpNeedDia,      //战盟祭坛科技升级需要的钻石:伤害减少
	ZmHunterUpNeedZySpNum,   //战盟狩猎场升级需要的卓越碎片基数
	ZmHunterUpNeedBzSpNum,   //战盟狩猎场升级需要的爆竹碎片基数
	ZmAddMemberCapNeedPoint, //增加1个成员容量上限需要的点数
	ZmSpeedUpBuildNeedPoint,
	ZmActiveBossNeedGp,
	ZmReliveBossFreeNum,
	ZmFreeAtkBossNum,       //每只战盟boss可免费挑战次数
	ZmFreeAtkBossNumGoldYk, //黄金卡每只战盟boss可免费挑战次数
	ZmSdBossNeedDia,
	ZmReliveBossNeedGpNum,
	ZmBossMaxHpRate,
	ZmMinJoinZmNeedLv,
	ZmSdKfBossMaxNum,
	GoldYkMyBossDayNum,
	GoldYkNormalXuYuanDayNum,
	OpenKfDayNum,
	
}
export const enum Err{
	ErrCode_Failed = 0,
	ErrCode_Success,
	ErrCode_DecodeDbDataErr,
	ErrCode_BadIp,
	ErrCode_AccountInvalid,
	ErrCode_AccountHasExsited,
	ErrCode_AccountNotExsited,
	ErrCode_AccountIsFreezed,
	ErrCode_AccountWrongPass,
	ErrCode_AccountNotLogin,
	ErrCode_ServerIdIsWrong,
	ErrCode_ServerIsStoped,
	ErrCode_RoleNameHasExsited,
	ErrCode_RoleNameEnValidate,
	ErrCode_RoleNotLogin,
	ErrCode_RoleIsOnline,
	ErrCode_RoleNotExsit,
	ErrCode_RoleIsFreezed,
	ErrCode_NotEnoughDia,
	ErrCode_SameRoleType,
	ErrCode_DbUpdateOneError,
	ErrCode_RoleHasNotCache,
	ErrCode_NotEnoughCap,
	ErrCode_PriceChanged,
	ErrCode_PageOutOffRange,
	ErrCode_ShopNotExsit,
	ErrCode_SuccessBuy,
	ErrCode_SuccessOrdered,
	ErrCode_NotEnoughItem,
	ErrCode_NotEnoughGold,
	ErrCode_SuccessLearnSkill,
	ErrCode_SuccessUpSkillLv,
	ErrCode_TeamNotExsit,
	ErrCode_TeamFull,
	ErrCode_RoleIsNotOnline,
	ErrCode_RoleHasAlreadyInTeam,
	ErrCode_RoleCanNotJoinTeam,
	ErrCode_NotEnoughLineTime,
	ErrCode_NotEnoughLv,
	ErrCode_ExitTimeNotLongEnough,
	ErrCode_HasBadWords,
	ErrCode_NotEnoughMuPoint,
	ErrCode_CanNotAtkTarget,
	ErrCode_AtkCdNotOk,
	ErrCode_EquipNotFound,
	ErrCode_TaskNotFound,
	ErrCode_TaskNotAchieved,
	ErrCode_TaskHasCompleted,
	ErrCode_NotEnoughNum,
	ErrCode_ChatTimeTooShort,
	ErrCode_MsgInvalid,
	ErrCode_ChatForbidden,
	ErrCode_CanNotHeCheng,
	ErrCode_CannotUseItem,
	ErrCode_UseItemFailed,
	ErrCode_HasPreOrders,
	ErrCode_TooManyRedPoint,
	ErrCode_FbIsClosed,
	ErrCode_NotEnoughFbNum,
	ErrCode_CannotCallBossInFb,
	ErrCode_LineIsFull,
	ErrCode_HoleHasExsited,
	ErrCode_HasNoCacheOtherHole,
	ErrCode_UnmarshalDataErr,
	ErrCode_ThisHoleGridIsOpenOver,
	ErrCode_RequestBuffFull,
	ErrCode_HasTooManyCallBoss,
	ErrCode_HasTooManyCallRedBoss,
	ErrCode_RoleTypeHasNotActive,
	ErrCode_BuffHoleIsFighting,
	ErrCode_StartSeizeBuffHole,
	ErrCode_EmptyBuffHole,
	ErrCode_OrderNotExsit,
	ErrCode_TooManyOrderNum,
	ErrCode_HasNewVersion,
}
// export const enum MT{
//     //==========【局部】==========
// 	WorldChat = 0,
// 	RoomChat,
//     TeamChat,
//     ZmChat,
//     LmChat,
// 	JoinRoom,
//     StartMoveTo,
// 	UpdateMyPos,
//     EndMoveTo,
// 	GetLineList,
// 	PlayerAtkOneMonster,
//     PlayerAtkMany,
//     CreateNewTeam5,
// 	TryPickup1DropItem,
// 	GetTeamInfoList,
// 	GetHasNoTeamOthers,
// 	ExitFromMyTeam,
// 	HitOutFromMyTeam,
// 	ClearMyTeamRequestList,
// 	SetMyTeamData,
// 	GetMyTeam,
// 	RequestJoinTeam,
//     GetMyTeamRequesterList,
//     Invite1toJoinTeam,
//     Agree1RequesterToJoinMyTeam,
//     IAgreeInvitedtoJoinTeam,
//     GetMyTeamSet,
//     ChangeLine,
//     BackToHome,
//     RelifeAtPlace,
//     RelifeAtHome,
//     ToRandomPosition,
//     SwitchAuto,

//     //===由服务器主动触发传递给客户端，服务端不注册路由与回调，客户端仅注册回调==
//     NewMonsterGointoMyDis= 500,
//     MonsterGoHome,
//     LeaveFromServer,
//     GetNewRoomMsg,
// 	GetNewTeamMsg,
// 	GetNewWorldMsg,
//     GetNewZmMsg,
// 	GetNewSystemMsg,
// 	AutoGetHpExp,
// 	MonsterAtkMe,
// 	MonsterIsDeath,
// 	NewTeamMenber,
// 	TeamMenberPickUp1Item,
// 	BeInvitedtoJoinTeam,
// 	JoinTeam,
// 	TeamMenberExit,
// 	MenberIsHitOutFromMyTeam,
// 	BeHitOutFromTeam,
// 	NewTeamOwner,
// 	Delete1DropItem,
//     Delete1DropGold,
//     ChangePosition,
//     MonsterAtkOther,
//     NewOtherGointoMyDis,
//     DeleteOtherPlayer,
// 	OtherIsRelifeAtPlace,
//     MonsterStartMoveTo,

//     //==========【Game全局】==========
// 	AccountRegist = 1000,
// 	AccountLogin,
// 	AccountChangePass,
// 	GetRoleList,
// 	TryCreatNewRole,
// 	CreatNewRole,
// 	LoginServer,
// 	ReLoginServer,
// 	KfChat,
//     DeleteRole,
// }